on: [push, pull_request]

name: Continuous Integration

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      
      - name: Run MongoDB in Docker
        run: docker run --name mongo -p 27017:27017 -d mongo:4.4.6

      - name: Run crawler
        run: go run . --day 1 --month 2 --profileNo 2
