on: [push, pull_request]

name: Continuous Integration

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: go run . --day 1 --month 2 --profileNo 2
